import { AxiosInstance, isAxiosError } from 'axios';
import { apiClient } from '../api/client';
import { ApiException, AppException, AuthException } from '../api/appException';
import { parseUser, User } from '../models/user';

export interface LoginResult {
  accessToken: string;
  refreshToken: string;
  user: User;
}

export interface RefreshResult {
  accessToken: string;
  refreshToken: string | null;
}

function bodyAsMap(data: unknown): Record<string, unknown> {
  if (data !== null && typeof data === 'object' && !Array.isArray(data)) {
    return data as Record<string, unknown>;
  }
  throw new ApiException(0, 'Unexpected server response');
}

function mapError(err: unknown): AppException {
  if (err instanceof AppException) return err;

  if (isAxiosError(err)) {
    const status = err.response?.status;
    const body = err.response?.data;
    const msg =
      body !== null && typeof body === 'object' && typeof (body as Record<string, unknown>).error === 'string'
        ? ((body as Record<string, unknown>).error as string)
        : null;
    // Use the server's error message if present (e.g. "Invalid credentials" on 401).
    // Only fall back to AuthException when there is no body; that means it was a
    // token-expiry 401 generated by the interceptor with no response body.
    if (msg != null) return new ApiException(status ?? 0, msg);
    if (status === 401) return new AuthException();
    return new ApiException(status ?? 0, 'Unknown error');
  }

  return new ApiException(0, 'Unknown error');
}

export class AuthService {
  constructor(private readonly client: AxiosInstance) {}

  async login(email: string, password: string): Promise<LoginResult> {
    try {
      const res = await this.client.post('/auth/login', { email, password });
      const data = bodyAsMap(res.data);
      const accessToken = typeof data.accessToken === 'string' ? data.accessToken : null;
      const refreshToken = typeof data.refreshToken === 'string' ? data.refreshToken : null;
      const userMap =
        data.user !== null && typeof data.user === 'object' && !Array.isArray(data.user)
          ? (data.user as Record<string, unknown>)
          : null;
      if (!accessToken || !refreshToken || !userMap) {
        throw new ApiException(0, 'Unexpected server response');
      }
      return { accessToken, refreshToken, user: parseUser(userMap) };
    } catch (err) {
      throw mapError(err);
    }
  }

  async register(email: string, password: string, fullName: string): Promise<User> {
    try {
      const res = await this.client.post('/auth/register', {
        email,
        password,
        full_name: fullName,
      });
      return parseUser(bodyAsMap(res.data));
    } catch (err) {
      throw mapError(err);
    }
  }

  async refresh(refreshToken: string): Promise<RefreshResult> {
    try {
      const res = await this.client.post('/auth/refresh', { refreshToken });
      const data = bodyAsMap(res.data);
      const accessToken = typeof data.accessToken === 'string' ? data.accessToken : null;
      if (!accessToken) {
        throw new ApiException(0, 'Unexpected server response');
      }
      return {
        accessToken,
        refreshToken: typeof data.refreshToken === 'string' ? data.refreshToken : null,
      };
    } catch (err) {
      throw mapError(err);
    }
  }

  async logout(): Promise<void> {
    try {
      await this.client.post('/auth/logout');
    } catch {
      // Ignore logout errors; clear local state regardless.
    }
  }
}

export const authService = new AuthService(apiClient);
