/* AUTO-GENERATED by ungdungdidong/gas_ews/export_firmware.py from
 * outputs_gas_ews/model_contract.json -- DO NOT EDIT BY HAND. Re-run the
 * exporter after retraining so firmware and model never disagree. */
#pragma once

/* QCVN 03:2019/BYT (ppm @25C, 1 atm) */
#define GAS_EWS_STEL_CO_PPM   34.916101f
#define GAS_EWS_TWA_CO_PPM    17.458051f
#define GAS_EWS_STEL_NO2_PPM  5.314524f
#define GAS_EWS_TWA_NO2_PPM   2.657262f

#define GAS_EWS_SLOT_MS          5000   /* sensor poll grid */
#define GAS_EWS_SLOTS_PER_STEP   2
#define GAS_EWS_WINDOW_STEPS     120   /* model input: 20 min */
#define GAS_EWS_NUM_CHANNELS     8
#define GAS_EWS_HORIZON_STEPS    60
#define GAS_EWS_STEL_STEPS       90
#define GAS_EWS_TWA_STEPS        2880
#define GAS_EWS_TWA_BUCKET_STEPS 6
#define GAS_EWS_PROJ_PAST_STEPS  30
#define GAS_EWS_PROJ_LEVEL_STEPS 6
#define GAS_EWS_FFILL_STEPS      6
#define GAS_EWS_STEL_MIN_VALID   6
#define GAS_EWS_GAP_SLOTS        12   /* offline > this many slots = reboot/outage */
#define GAS_EWS_WARMUP_SLOTS     120   /* MOS preheat ignored after it */

#define GAS_EWS_T_REF    28.0f
#define GAS_EWS_T_SCALE  5.0f
#define GAS_EWS_RH_REF   70.0f
#define GAS_EWS_RH_SCALE 20.0f

/* Early warning (chosen on VAL): model p >= GAS_EWS_THR_MODEL_* OR
 * persistence projection / STEL >= GAS_EWS_THR_PROJ_*; QCVN rule always on. */
#define GAS_EWS_THR_MODEL_CO   0.9000f
#define GAS_EWS_THR_MODEL_NO2  0.0500f
#define GAS_EWS_THR_PROJ_CO    1.5000f
#define GAS_EWS_THR_PROJ_NO2   0.6000f
#define GAS_EWS_DEBOUNCE_ON    2   /* consecutive steps to raise */
#define GAS_EWS_DEBOUNCE_OFF   30  /* consecutive steps to clear */

#define GAS_EWS_SENSOR_CAP_CO_PPM  5000.0f
#define GAS_EWS_SENSOR_CAP_NO2_PPM 10.0f

/* Channel order (model input last dim): co_rel, no2_rel, co_stel_rel, no2_stel_rel, co_proj_rel, no2_proj_rel, temp_norm, rh_norm */
#define GAS_EWS_MODEL_PARAMS 12186
#define GAS_EWS_MODEL_BYTES  20896
