/* incident_domain.h - GENERATED by spec/incident/gen from spec/incident/deployments. DO NOT EDIT.
 *
 * Selected by the Kconfig choice SA_INCIDENT_ENV. An empty verifying contract
 * means that deployment does not exist yet; the incident module then refuses
 * to sign instead of signing for a wrong domain.
 */
#pragma once

#define INCIDENT_DOMAIN_NAME "AirSafetyLog"
#define INCIDENT_DOMAIN_VERSION "1"

#if defined(CONFIG_SA_INCIDENT_ENV_LOCAL)
#  define INCIDENT_DEPLOYMENT_NAME "localhost"
#  define INCIDENT_CHAIN_ID 11155111ULL
#  define INCIDENT_VERIFYING_CONTRACT "0x5FbDB2315678afecb367f032d93F642f64180aa3"
#  define INCIDENT_DOMAIN_SEPARATOR "0x3696d3186087b7d951859d495019cfe08620f9b7b134ed4a7678f80312879bc2"
#elif defined(CONFIG_SA_INCIDENT_ENV_SEPOLIA)
#  define INCIDENT_DEPLOYMENT_NAME "sepolia"
#  define INCIDENT_CHAIN_ID 11155111ULL
#  define INCIDENT_VERIFYING_CONTRACT "0x45CF175ffd4B1Ad77E87389d1e92945f9Bc88d3A"
#  define INCIDENT_DOMAIN_SEPARATOR "0x34632810b8dcf18cf8dd255b5d3c1f722d5879ef9535ff95abd5a17048ab485d"
#else
#  define INCIDENT_DEPLOYMENT_NAME "none"
#  define INCIDENT_CHAIN_ID 0ULL
#  define INCIDENT_VERIFYING_CONTRACT ""
#  define INCIDENT_DOMAIN_SEPARATOR ""
#endif
